services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  tcp-simulator:
    extends:
      file: docker-compose.yml
      service: tcp-simulator

networks:
  vcs-network:
    driver: bridge
    name: vcs-network

volumes:
  postgres_data:
    name: vcs-sms-postgres-data
  redis_data:
    name: vcs-sms-redis-data
  es_data:
    name: vcs-sms-es-data